### ISSUE TITLE
Not working again

### ISSUE THREAD

**Issue by aarongustafson** [apelsinet/worldnews-10k#2]
It might be a good idea to run the scrape in the background and present something while it’s running, rather than an error.

**Comment by aarongustafson** [comment]
And it’s back. I would definitely recommend a batter fallback for when there’s nothing. Even using ServiceWorker to cache the previous request might help.

**Comment by apelsinet** [comment]
Hi Aaron, thanks for your input! I've made lots of updates to make the project more robust since I submitted this, one is running the scraper as its own node process. This project only builds on POSIX as of the latest bunch of commits and I'll have to try it out myself on an azure instance tonight to see if I can get it to build there as well. There is a working live example on https://readworld.news that's up to date.

**Comment by apelsinet** [comment]
I've now added support for azure once again with my latest commit. If you wish to review an updated version of this project submission, please pull the current version. It should work on a clean azure instance without any dependencies globally installed. Just npm install and run, let the scraper output "JSON file written" and everything should work flawlessly, at least it does on my preview azure instance here: http://ed53002f-0ee0-4-231-b9ee.azurewebsites.net/ 
Thanks again :)
